language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: hk6GdyivkKTpposnxhhpeCeF1LcS9RSR/vu+MRAlJvJgCT2ieSvS9KlpXd7j1UWJxrZXLyQzjXk9RdFZdsnba8Ju/r/yrmgxSPCf5E4ENcq/AgO5z9KbXwgA+twFRF6HDu6MSdm0KEwA5UGw5WGUE6Y9UOdabpOj1EmWjd/vKfcPbVhLh502g4jv4VyJp2punXYZaI4pGeLp3r7wu9iWcbug//KAn0F8IaxGT5SwcDM8pHNzZrxCuBNVrAxkvoscnEb2XJfhEHHKcFmyT2j2vfwmj1BeMeBLsBsWK+utTPQlE0AWOhPEFILKdJLuBbjKz5P0xg5ZrJnMlDurDqE+G1Mt77Bb1WxfDMeeFwdSCgu4c73Mh2JycQqa+ulgpj87LUeUhqZiYD3Utt0PuK2tPM5GP/2EYqTHCeOhBafYo2I7jFb4OruAsfAzRpl95UpN1tq+1IWazDaqbbOMZLrIHIemxSpSdXvy2LSfstb+4JFiG2x6hEPqSRlbyRYqGFrU06TN40xYK02iHXYt67XdHUw8O3vx4V+q9zSSjaWJ7T8Kpvg53fATdah0WgP2hNW79pVuo/8/zCpnyGP1xR8ffy9uuQij8aL3h6vBWgqtQZByN8f4GfSkCsGIUC/vA7q55ieZjwOcsra1SJKJmMzjyOiWpSCJTIbvcb8rjAMlIEQ=
  app: calm-escarpment-51268
  on:
    repo: velafarq/note-book-app
